# Generated by Django 5.2.6 on 2025-09-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назавние фильма')),
                ('release_year', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='Длительность фильма(мин.)')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
