# Generated by Django 5.2.6 on 2025-09-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_favoritefilm'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название зала')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='Вместимость')),
                ('has_3d', models.BooleanField(default=False, verbose_name='3D')),
            ],
            options={
                'verbose_name': 'Кинозал',
                'verbose_name_plural': 'Кинозалы',
            },
        ),
    ]
